spring:
  application:
    name: hotel-event-reservation-system
  
  # Database Configuration for XAMPP MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_event_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
  # Mail Configuration (Mock for development)
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: your-mailtrap-username
    password: your-mailtrap-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /

# Logging Configuration
logging:
  level:
    com.hotel: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Application Configuration
app:
  qr:
    base-url: http://localhost:8080
    size: 300
  booking:
    confirmation-deadline-hours: 24
  notification:
    email-enabled: true
    sms-enabled: false
    cleanup:
      enabled: true
      days: 30
